- src/PlatformsManager.js
Package tool can support Debian/Ubuntu Linux as well.
> Add Debian package tool backend support

- android/lib/AndroidPlatform.js
Run sanity test and bump warning to versions > 15.
BUG=XWALK-4230
> AndroidPlatform: Integrate Crosswalk 15

- package.json
So npm will correctly install it.
> Make sure to include the windows/ directory in package.json

- android/lib/AndroidPlatform.js
Make our flag landscape and portrait same than in android api.
We should think why user controlled mode is not working
because that is maybe better in user perspective but
this is fine for now.
BUG=XWALK-5199
> Android: Fix sensor controlled app orientation

- android/lib/AndroidPlatform.js
- src/util/Download01Org.js
- test/download-01-org.js
- windows/lib/WinPlatform.js
Enhance Download01Org so it can handle different platforms.
Hook up downloader in WinPlatform.
To try: node ..\crosswalk-app-tools\src\crosswalk-pkg --crosswalk=canary --platforms=windows --manifest=win.downloader.works test-app\
BUG=XWALK-5288
> Windows: Enable crosswalk download

- src/Main.js
- src/crosswalk-pkg
> crosswalk-pkg: Persist --platforms parameter in the manifest

- src/util/Download01Org.js
> Downloader: Fix iteration through empty channels

- src/util/CrosswalkDir.js
- src/util/Version.js
- src/util/index.js
- windows/lib/WinPlatform.js
> Windows: Allow passing a directory to build crosswalk against

- src/CommandParser.js
- src/Main.js
- src/Manifest.js
> Main: Command "manifest" takes --platforms parameter now

- android/lib/AndroidPlatform.js
- android/test/android-sdk.js
- src/LogfileOutput.js
- src/Main.js
- src/OutputIface.js
- src/OutputTee.js
- src/TerminalOutput.js
- src/crosswalk-pkg
- src/util/Download01Org.js
- test/downloader.js
- test/logfile-output.js
- test/template-file.js
- windows/lib/WinPlatform.js
Introduce an optional parameter "path" for
OutputIface.info(msg, path). The TerminalOutput implementation
makes sure that the total output is not over 80 chars when a
path is passed.
BUG=XWALK-5585
> Output: Truncate output to 80 chars

- src/util/Version.js
> Version: Use correct path variable to load VERSION file

- android/lib/AndroidPlatform.js
> Android: Build all available ABIs, rather than hardcoding arm and x86

- android/lib/AndroidPlatform.js
The parameter for crosswalk-pkg is --android="lite",
for crosswalk-app use --android-shared.
BUG=XWALK-4972
> Android: Implement support for crosswalk-lite

- android/lib/JavaActivity.js
- src/FiniteProgress.js
- src/InfiniteProgress.js
- src/TerminalOutput.js
* Errors should be red.
* Warnings dark grey to stand out from the normal text.
* Fix spurious blank lines when a warning occurs during progress output.
BUG=XWALK-5640
> Output: Improve console output

- android/lib/AndroidPlatform.js
Fix needed after addition of --targets parameter.
BUG=XWALK-5641
> Android: Fix build against crosswalk-lite

- windows/lib/WixSDK.js
This prevents from generating too long file ids that are not supported by WIX.
BUG=XWALK-5679
> Use hash sums for WIX file ids

- windows/lib/WinPlatform.js
- windows/lib/WixSDK.js
> Windows: Pass command-line args from manifest to executable

- src/PlatformBase.js
- src/crosswalk-pkg
- windows/lib/WinPlatform.js
- windows/lib/WixSDK.js
By passing --platforms="android windows", both APKs and MSI are
now built. Woot.
BUG=XWALK-4499
> -pkg: Implement multi-platform build

- android/lib/AndroidPlatform.js
- android/test/main.js
Eliminate extensions-config.json.
BUG=XWALK-5756
> Change the way packing Android external extensions.

- src/Application.js
- src/Manifest.js
- src/PlatformBase.js
- src/crosswalk-pkg
- src/util/index.js
- windows/lib/WixSDK.js
Hi, Robert. I have wend through the process to get a bundle.
My test sample:
https://drive.google.com/a/intel.com/file/d/0B_e_Mp4JYfsreHV2SjRDd2RzaEU/view?usp=sharing
> Hooks app tools part

- src/crosswalk-pkg
Target platform default was android, read it from the manifest
instead, and only if that fails, default to android.
BUG=XWALK-6398
> -pkg: Default to target platforms from manifest

- src/crosswalk-pkg
- src/util/Keys.js
- src/util/index.js
- test/keys.js
- windows/lib/WinPlatform.js
- windows/lib/WixSDK.js
> Xwalk 6459

- src/crosswalk-pkg
> -pkg: Tweak help text

- windows/lib/WixSDK.js
Entry IDs would be created using the filename component of a path
only, so if the same filename occurred in different paths, the
same ID would result, and cause WiX to fail.
Now the ID is created using a file's absolute path, which is
guaranteed to be unique.
BUG=APPTOOLS-43
> Windows: Avoid collision of entry IDs for WiX

- android/lib/AndroidSDK.js
- windows/lib/WinPlatform.js
Converts the data buffer from `child_process.stdout` to a string if necessary.
> Buffer.toString
