src/PlatformBase.js

After a backend has built a target package, it should export the package
into 'pkg' directory, if there already exists one package in it, the
'PlatformBase' should replace it with the new one.
BUG=#30

Force to replace the old package

---

Gruntfile.js
android/lib/CrosswalkZip.js

Override was implemented on the wrong class by accident.
Also update docs.
BUG=XWALK-4250

CrosswalkZip: Move toString() to the Version inner class

---

package.json

Removes the warning "npm WARN package.json crosswalk-app-tools@0.7.0 license should be a valid SPDX license expression" on npm install

Make license identifier SPDX compliant

---

src/Manifest.js

When field xwalk_app_version is invalid, do not attempt to continue
but just throw an error. There is no way to recover anyway.
BUG=XWALK-5255

Manifest: Throw error on invalid xwalk_app_version

---

src/CommandParser.js
src/Main.js
src/Manifest.js
src/crosswalk-pkg

By passing -m / --manifest=<package-id> to crosswalk-pkg, one can
forgo needing a minimal manifest.json, it will created and filled
with the package-id and other default values.
backport-candidate
BUG=XWALK-5167
BUG=XWALK-5257

Android: Allow passing package-id to crosswalk-pkg

---

windows/lib/WixSDK.js

-For the record ffmpegsumo is gone on all platforms it used to exist
BUG=XWALK-5285

Windows: Remove ffmpegsumo.dll relative record

---

src/FiniteProgress.js
src/InfiniteProgress.js
src/LogfileOutput.js
src/Main.js
src/OutputIface.js
src/OutputTee.js
src/TerminalOutput.js
src/util/Download01Org.js
test/logfile-output.js
test/output-tee.js

When a channel does not exist (e.g. stable channel when only
canary builds have been published yet), do not fail, but just
keep iterating through channels like normal.
BUG=XWALK-5289

Downloader: Do not fail on empty channel

---

src/Manifest.js

Print the name of the manifest member when an unsupported value is specified.
Note: while testing this I noticed that the warnings are printed twice, but it doesn't seem related to this PR.
BUG=XWALK-5262

Improve warning message when manifest fields are invalid

---

src/crosswalk-pkg

E.g. passing --android="shared" builds a package depending on the
shared crosswalk APK in Google Play Store.
BUG=XWALK-5259

crosswalk-pkg: Add args -a --android for platform-specific config

---

android/lib/AndroidPlatform.js
src/crosswalk-pkg
src/util/Download01Org.js
src/util/Downloader.js
test/download-01-org.js

App-tools would hang in the end when iterating through empty
channels, like stable/beta for windows and lite. Fix this by
aborting the index page download on an error response (e.g. 404).
BUG=XWALK-5568

Android: Improve downloader for empty channels

---

windows/lib/WixSDK.js

Starting with build 17.45.426.0 we're shipping few extra DLLs
which are needed for WebGL support. This patch make sure we
pack them in the final .msi.
BUG=XWALK-5506, XWALK-4982

Make sure to pack OpenGL dll files with the application.

---

android/lib/AndroidPlatform.js
android/lib/AndroidSDK.js
examples/crosswalk-app-tools-backend-demo/lib/DemoPlatform.js
src/CommandParser.js
src/Main.js
src/PlatformBase.js
test-util/TestPlatform.js
test/command-parser.js
test/main.js
test/platform-base.js
test/platform-info.js
windows/lib/WinPlatform.js

Those commands are not needed any more, because with crosswalk-pkg a
new project is created every time. Commands "clean" and "refresh" were
not implemented yet anyway, close tickets in JIRA.
BUG=XWALK-4153, XWALK-5596

Commands: Remove "clean", "update" and "refresh" commands

---

android/lib/AndroidPlatform.js
src/crosswalk-pkg

Always take last command-line parameter as html app directory. This
allows -r to be passed without value, e.g. crosswalk-pkg -r <path>.
BUG=XWALK-5592

-pkg: Better argument handling

---

src/crosswalk-pkg

When adding this parameter to the command-line, the build tree
will not be deleted at the end of the packaging run, but kept
for analysis and debugging.
BUG=XWALK-5604

-pkg: New parameter -k / --keep to keep build tree

---

src/crosswalk-pkg

When building APKs, only check android setup, and vice versa for
windows. Checking for all backends creates error messages that
are not just confusing.
BUG=XWALK-5606

-pkg: Only check host setup for target platforms

---

src/crosswalk-pkg

For testing purpose the manifest data can be passed to crosswalk-pkg
as a string. Please not that at least the xwalk_package_id field
needs to be included in the manifest data.
BUG=XWALK-5618

-pkg: Support passing manifest data via -m / --manifest

---

android/data/AndroidManifest.xml.tpl
android/lib/AndroidManifest.js
android/lib/AndroidPlatform.js
android/lib/JavaActivity.js

The main java activity class was always named "MainActivity" in our
built apps, but for easier automated testing with QAs tools we want
to have the name be derived from the package-id. So for example for
package-id of "com.example.foo", we now derive the activity class
name as FooActivity, using the last component case-modified, with
"Activity" suffix.
BUG=XWALK-5014

Android: Derive activity name from package-id

---

src/crosswalk-pkg

Short-form parameter -a was not hooked up to work like --android.
BUG=XWALK-5682

-pkg: Respect command-line parameter -a

---

android/lib/AndroidPlatform.js
android/lib/XmlTheme.js
android/test/xml-theme.js
package.json
src/Manifest.js
test/manifest.js

Default background_color is #ffffff (white). If a different colour
is set, it is displayed during the application startup, using the
"xwalk launch screen" theming infrastructure (theme.xml,
launchscreen_bg.xml).
Also add unit tests for Manifest, XmlTheme classes.
BUG=XWALK-5648

Manifest, Android: Support manifest background_color

---

android/lib/AndroidPlatform.js
android/lib/XmlTheme.js

During startup, show the web manifest background_color (or white)
and put the application icon in the centre.
BUG=XWALK-4692

Android: Use icon as default splash screen

---

android/lib/AndroidPlatform.js
src/util/CrosswalkDir.js
src/util/CrosswalkZip.js

Otherwise the semantics of zip extraction and ShellJS recursive
copy do not match.
BUG=XWALK-5823

Android: Create target dirs only when importing zip, not dir

---

android/lib/AndroidPlatform.js

Even without .js file, the extension should be packaged into apk.
Because when loading extensions, Crosswalk will try to create the jsapi
content automatically based on the extension Java class annotations for
such type of extension.
BUG=XWALK-5825

Support packaging extensions(Java) without .js file

---

android/lib/AndroidSDK.js

When there is a whitespace in the patch to apache ant, such as in
C:\Program Files\... then building packages fails. Instead just
exec "ant" without path, to avoid this problem.
BUG=XWALK-5894

Android: Exec "ant" without path

---

package.json

grunt-cli is needed for "npm test" to run

Add grunt-cli to devDependencies

---

src/CommandParser.js
src/Main.js
src/Manifest.js
src/crosswalk-pkg
test/main.js
test/manifest.js

Also internal clean up so that crosswalk-app will be able to build
only for single target platforms, while crosswalk-pkg will support
multiple targets.
BUG=XWALK-5909

-app: Take only single target --platform

---

package.json

The ```node_modules/grunt-cli/bin/``` path in the npm test command is unncessary and makes ```npm test``` fail on Windows hosts. Removing it solves that problem.
Tested that ```npm test``` still works on OS X.

Remove unnecessary node_modules/grunt-cli/bin/ path from npm test

---

windows/lib/WinPlatform.js
windows/lib/WixSDK.js

When not explicitely building a release MSI, right-click on the
crosswalk app shows a menu to launch the chromium inspector.
BUG=XWALK-5188

Windows: Enable inspector for debug builds

---

src/FiniteProgress.js

Suppress all the extra output on every downloaded chunk when the
change is not enough to fill another step in the progress bar.
BUG=XWALK-5949

Output: Only print progress output when it has changed

---

windows/test/main.js

Makes "nodeunit /windows/test" pass

Windows: Change 'platforms' to 'platform' when testing 'create'

---

Gruntfile.js
windows/lib/WixSDK.js

The Windows sources were missing from the Grunt jshint files, I added them and fixed a few errors that were reported.

Windows: add windows sources to jshint and fix lint errors

---

Gruntfile.js
android/test/main.js
test/main.js

The main purpose of this PR is to run Windows tests when ```npm test``` is running on Windows, in addition to the Android tests. To achieve this:
* build and create Android tests are moved out of ```test/main.js```. The top-level ```test``` folder only includes platform-agnostic tests
* build and create Android tests are added to ```android/test/main.js```
* ```Gruntfile.js``` contains three subtasks for the nodeunit task, ```common```, ```android``` and ```windows```. They can be run individually with e.g. ```grunt nodeunit:common```, or all at once with ```grunt nodeunit``` (what ```npm test``` does)
* The ```windows``` task is empy if not running on windows
BUG=XWALK-5955

test: refactor test sources and run Windows tests if platform is Windows

---

.travis.yml

Enable integration with the Travis CI infrastructure (www.travis-ci.org).
After this PR is merged, any push to the repository will trigger common and Android unit test on Linux host. Results will be visible at https://travis-ci.org/crosswalk-project/crosswalk-app-tools
Test runs will be triggered on PR submission as well, but ONLY if the PR is from a branch within the same upstream repository. This is a restriction imposed by Travis for security reasons.
Related to (but doesn't completely fix) XWALK-5889

Enable CI for Linux host on Travis-CI

---

appveyor.yml

Enable integration with the Appveyor CI infrastructure (www.appveyor.com).
After this PR is merged, any push to the repository will trigger common, Android and Windows unit tests on Windows host. Results will be visible at https://ci.appveyor.com/project/crosswalk-project/crosswalk-app-tools.
Test runs will be triggered on PR submission as well.
Related to (but doesn't completely fix) XWALK-5889

Enable CI on Windows hosts with Appveyor

---

android/lib/AndroidPlatform.js

The --android-targets parameter allows passing of target ABIs to
build for. Only ABIs that are part of the same release can be
passed together. Currently we have one release for 32bit ABIs
(armeabi-v7a, x86) and one for 64bit (arm64-v8a, x86_64).
Example: --android-targets="armeabi-v7a x86"
BUG=XWALK-5999

-app: Fix handling of --android-targets

---

windows/lib/WinPlatform.js
windows/lib/WixSDK.js

Combine all the extensions into "xwalk-extensions" sub-directory
of the packaged application.
BUG=XWALK-4851

Windows: Support packaging of external extensions by manifest file

---

android/lib/AndroidPlatform.js

Targets support for crosswalk-app broke the default behaviour by
overriding already parsed targets with undefined. Fix return
value to respect existing value.
Oh boy. Most stupdid bug of 2016 already.
BUG=XWALK-6016

Android: Fix handling of -t / --targets parameter

---

.travis.yml
appveyor.yml
lint.py

Failure analysis:
https://crosswalk-project.org/jira/browse/XWALK-5171
- Enable 26 QA android 32-bits tests for Linux host on Travis-CI
- Enable 26 QA android 64-bits tests for Linux host on Travis-CI
- Enable 9 QA ios tests for OSX host on Travis-CI
- Enable ios nodeunit tests for OSX host on Travis-CI by command: 'grunt nodeunit:common'
- Enable 15 QA windows tests on Appveyor
- Enable 10 QA android 32-bits tests on Appveyor
- Enable 10 QA android 64-bits tests on Appveyor
- Android 64-bit testing on travis and android testing on appveyor are blocked by emulator issue, we skip checkpoints of emulator dependency
- Android 32bit and 64bit testing on appveyor waste too much time, we reduce the crosswalk-app tests
https://crosswalk-project.org/jira/browse/XWALK-5889

Enable QA tests for Travis and Appveyor CI

---

src/crosswalk-pkg

The combination of shared and 64bit is undefined, shared is always
ABI independent.
BUG=XWALK-6213

-pkg: Ignore -t / --targets for shared android build

---

src/crosswalk-pkg

Even if targets were invalid, they would override, the default
targets would not be used, ending up with empty targets. Now the
custom passed targets are only respected and used after they
have been found valid, otherwise default is kept.
BUG=XWALK-6375

-pkg: Fix validation of -t / --targets

---

android/lib/AndroidManifest.js

By default, xwalk_android_permissions from manifest.json are added
to AndroidManifest.xml with a namespace of android.permission. But
if permissions already have a namespace, keep it, and do not add
the android one too.
BUG=XWALK-6214

Android: Improve permissions handling

---

src/util/Download01Org.js

Windows releases now start with crosswalk64-, so take that into
account when fetching the zip. This change came with the automated
windows builds.
BUG=XWALK-6567

Windows: Fix download after release filename change

---

android/lib/AndroidPlatform.js

Lite only has Canary release.
Remove the 'lzma -d' decompress part which is no use.

Error fix, to support Crosswalk-Lite.

---

windows/lib/WixSDK.js

Rather than installing all files from an extension directory, only
use the ones with .dll suffix in the WiX installer. So other files
part of the extension (aux, development, etc) do not cause
conflicts
BUG=XWALK-6465

Windows: Only install .dll files from extensions

---

windows/lib/WinPlatform.js

App-tools supports building against an unzipped crosswalk release.
The dirname needs to passed through -c. This feature was broken
with the recent auto-build changing filename from crosswalk-<version>
to crosswalk64-<version>.
This change derives the crosswalk version from the VERSION file
inside, rather than the directory name, so it works again.
BUG=XWALK-6596

Windows: Fix building against crosswalk dir

---

windows/lib/WixSDK.js

We used to have a whitelist of dll files, that should go into the
MSI. But it is more sustainable to just ship all of them.
BUG=XWALK-6575

Windows: Package all dll files

---

windows/lib/WinPlatform.js
windows/lib/WixSDK.js

Create the .wxs file in the project root directory rather than
current dir, so extension hooks can access, modify and repackage.
BUG=XWALK-6606

Windows: Create WiX wxs file in project root

---

android/lib/AndroidPlatform.js

The way to pick target API was to set the respective JNI libs
directory readable/unreadable. This does not work on windows,
so we always built fat APKs.
So we are changing strategy, and the skipped ABIs' libxwalkcore.so
are renamed to libxwalkcore.so.foo, such that ant does not consider
them.
BUG=XWALK-6470

Android: Disable unused ABIs by libxwalkcore.so, not directory

---

windows/lib/WixSDK.js

It's required to get the notifications working and documented
by Microsoft (this is valid only here because Crosswalk is not
an UWP app).

[Windows] Set the System.AppUserModel.ID on the shortcut

---

appveyor.yml
lint.py

It may be a firewall issue with DownloadFile in Appveyor VM
- Use Start-FileDownload to download files in appveyor.yml
- Use urllib2.urlopen to download files in lint.py

Fix Appveyor Download issue

---

android/lib/AndroidPlatform.js

We have a libxwalkcore.so and libxwalkdummy.do for each supported
target architecture. The non-matching dummy lib also needs to be
skipped when building, to not confuse the JNI loader.
BUG=XWALK-6725

Android: Also skip dummy JNI lib

---

src/crosswalk-pkg

Handle test case when building app without manifest, passing
package-id via command-line. When platform is not specified in this
case, default to android.
BUG=XWALK-6698

-pkg: Default to android target platform

---

appveyor.yml

Ant release 1.9.7 was published and 1.9.6 was removed. Need to find a more resilient way to handle this, but for now I'm patching it so that releases can continue.

CI: update ant release used in the appveyor VM

---

lint.py

We were currently invoking the Python unit test files with
`os.system()` (which is bad in itself) without bothering to check its
return code.
In practice, this meant that `lint.py` always exited with 0 regardless
of whether the unit tests it invoked passed or not.
While here, stop redirecting output on Linux to a file called "null".

lint.py: Exit with the status code of the unit tests.

---

src/TerminalOutput.js

When not running in an interactive terminal, do not truncate paths
but write full output for complete logfiles.
BUG=XWALK-6826

Output: Do not truncate to 80 when non-interactive

---

appveyor.yml

Android 32bit and 64bit testing on appveyor are blocked by wasting more than 60 minutes, so divide into two jobs

Divide android 32bit and 64bit testing on appveyor

---

windows/lib/WinPlatform.js
windows/lib/WixSDK.js

When pulling crosswalk into the build tree use recursive copying, such
that the "locales" folder with its contents is not skipped.
BUG=APPTOOLS-339

Windows: Use recursive copy when importing crosswalk

---

src/crosswalk-pkg

After all the args have been evaluated, check for left-over ones
and print an error message that they have not been handled.
This helps finding typos in the command-line.
BUG=XWALK-6807

-pkg: Warn about unrecognised cmd-line args

---

windows/lib/WixSDK.js

Previously the app name was used for product name as well. But there is
a limitation for the latter, it does not accept a name made only of
numeric digits. To mitigate this, always create the product name by
combining vendor and app name.
BUG=APPTOOLS-338

Windows: Create product name from vendor and app name

---

android/lib/AndroidPlatform.js

When creating a crosswalk-lite apk, lib/ has all ABIs (armv7 and x86 by
default), so there is no size win. Now also use the ABI skipping logic
for crosswalk lite by considering libxwalkcoreCompressed.so.
BUG=APPTOOLS-341

Android: Only package single ABI for crosswalk-lite

---

README.md
src/crosswalk-pkg
windows/lib/WinPlatform.js

Add command-line option -s / --skip-check. By default, host check is
only enabled when running on an interactive terminal. Using this
parameter, the check can be skipped.
For forcing host check on non-interative systems such as CI, pass
the paramter "-s no" / "--skip-check=no".
BUG=APPTOOLS-303

-pkg: Option -s / --skip-check to skip host check before building

---

windows/lib/WixSDK.js

Due to inadvertedly using recursive search for .pak files, they
ended up in the MSI twice: once when actually being added, and
also when the high-dpi assets files (also in .pak format) were
being added.
Fix this by using non-recursive directory listing in both cases.
BUG=APPTOOLS-342

Windows: Do not package locale .pak files twice

---

android/lib/JavaActivity.js

We used to use file:// but that has security implications.
BUG=APPTOOLS-345

Android: Always load app using app:// protocol

---

windows/lib/WixSDK.js

Instead of using C:\Program Files\vendor\appname to store the
application files we now use C:\Program Files\vendor\approot.
The idea behind this change is that no matter the app name the
application files will be located always at the same place. The work
is in preparation of support for Project Centennial where applications
don't have command line arguments so Crosswalk needs to be able to find
its manifest file automatically relative to its own path.

Windows: Change installation path of application files.

---

test/download-handler.js
test/downloader.js

The Linux Foundation URL used to test the download handler needs to be changed to https otherwise it'll return an error.

[Test] Fix download tests

---

appveyor.yml

Change the download method by replacing Start-FileDownload with 'appveyor DownloadFile' for 7z and zip format files.

AppVeyor-CI: Fix download hanging issue

---

windows/lib/WixSDK.js

XWalk locales are now located in locales/xwalk instead of locales/
Special case here by checking the new path and then the old path if
the new path doesn't exist. It will avoid to sync the app-tool release
with the version of Crosswalk after 4d6074.
BUG=APPTOOLS-363

windows : fix breakage after 4d6074 which moves the locales files.

---

src/crosswalk-pkg

Clarify that single characters options shouldn't be followed by '='
BUG=APPTOOLS-372

Clarify usage of command line options in help message

---

package.json
src/util/index.js
windows/lib/WixSDK.js

Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …

Update uuid to version 3.0.0
